#!/bin/bash
cd test_deliverable

for item in $(cat testnames.txt); 
do
	echo TESTING $item; 
	make -B -s our/$item;
	our/$item
	RES=$?
	echo $RES
	if [ $RES -eq 0 ]; then
       echo -e "\e[1m\e[32mSUCCES\e[0m"
    else
	    echo -e "\e[1m\e[31mFAIL\e[0m"
    	exit 1;
    fi


	echo $res;
done;