#!/bin/bash

make bin/c_compiler
cd test_deliverable
make endings > /dev/null 2> /dev/null

bad=0;

for item in $(cat testnames.txt); 
do
	echo -e -n "\e[1m\e[34m$item\e[0m,"
	make -B -s $1/$item > /dev/null 2> /dev/null
	compiled=$?;
	if [ $compiled -ne 0 ]; then
    	echo  -e " ,\e[1m\e[31mCOMPILATION FAILED\e[0m"
    	bad=$((bad+1))
	else
		qemu-mips $1/$item
		RES=$?
		echo -n "$RES,"
		if [ $RES -eq 0 ]; then
	    	echo -e "\e[1m\e[32mSUCCES\e[0m"
	    else
	    	echo -e "\e[1m\e[31mFAIL\e[0m"
	    	bad=$((bad+1));
	    fi
	fi
done;
exit $bad;
